language: node_js

node_js:
  - "node"
  - "6"
  - "7"
  - "8"
  - "9"

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm --version"

install:
  - npm install

script:
  - npm test
