language: node_js

node_js:
  - "node"
  - "6"
  - "7"
  - "8"
  - "9"

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm --version"

install:
  - npm install
  - npm install if-ver -g
  - npm install codacy-coverage coveralls -g

script:
  - npm test

after_success:
  - "cat coverage/lcov.info | coveralls"
  - "cat coverage/lcov.info | codacy-coverage"
